### ISSUE TITLE
[Request] Disable temporarily when Darkmode is toggled manually

### ISSUE THREAD

**Issue by NICHOLAS85** [Skittyblock/LightsOut#2]
I like this tweak but sometimes I like switching dark mode off when it's dark for certain situations and unfortunately, this tweak makes that impossible as the sensor immediately switches dark mode back on. 

A solution I thought of would be simply disabling the tweak temporarily when I toggle dark mode manually and it reenabling itself the next time the device unlocks.

**Comment by Skittyblock** [comment]
Thanks for the feature suggestion! I just added it. Sorry it took so long :)

**Comment by NICHOLAS85** [comment]
Thanks!
